name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: fharlup  # Replace with your actual username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/fharlup/berework  # Ensure this is correct
            git pull origin main
            npm install
            pm2 restart my-backend || pm2 start server.js --name my-backend
            pm2 save
