name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ihear_main  # Replace with your actual username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Navigating to project folder..."
            cd /home/fharlup/berework  # Ensure this is correct

            echo "🔄 Pulling latest code..."
            git pull origin main

            echo "📦 Installing dependencies..."
            npm install

            echo "🛑 Stopping existing PM2 process (if running)..."
            pm2 stop my-backend || true
            pm2 delete my-backend || true

            echo "🚀 Starting PM2 process..."
            pm2 start server.js --name my-backend

            echo "💾 Saving PM2 process..."
            pm2 save
            pm2 list
